name: Build Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:

  build:
    name: Build game
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permissions for publish.sh (Linux/macOS)        
        run: chmod +x tools/publish.sh

      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run the publish script
        run: tools/publish.sh

      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Game-Build-windows
          path: src/Game.Desktop/bin/Release/net8.0/win-x64

      - name: Upload mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: Game-Build-osx-arm
          path: src/Game.Desktop/bin/Release/net8.0/osx-arm64

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Game-Build-linux
          path: src/Game.Desktop/bin/Release/net8.0/linux-x64

  release:
    name: Release game
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token: ${{ github.token }}
          output-file: 'CHANGELOG.md'
          skip-version-file: 'true'
          skip-commit: 'false'
          git-push: 'true'
      
      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: Game-Build-windows
          path: ./tools/Output/windows
      
      - name: Create Zip for Windows
        run: zip -r Game-Build-windows.zip ./tools/Output/windows

      - name: Download Linux build
        uses: actions/download-artifact@v4
        with:
          name: Game-Build-linux
          path: ./tools/Output/linux
            
      - name: Create Zip for Linux
        run: zip -r Game-Build-linux.zip ./tools/Output/linux

      - name: Download Mac build
        uses: actions/download-artifact@v4
        with:
          name: Game-Build-osx-arm
          path: ./tools/Output/mac
            
      - name: Create Zip for Mac
        run: zip -r Game-Build-mac.zip ./tools/Output/mac

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.tag != '' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          files: |            
            LICENSE
            Game-Build-windows.zip
            Game-Build-linux.zip
            Game-Build-mac.zip